# Description
#   Hubot script
#   KURUMI-chan Dictionary
#
# Configuration:
#   None
#
# Commands:
#   See below
#
# Author:
#   Hisashi Kumazawa <hisashi.kumazawa@gmail.com>

module.exports = (robot) ->

# robot.hear /単語/i, (msg) -> msg.send "説明"
  robot.hear /ゾラリズム/i, (msg) -> msg.send "自然主義的な実験小説作法ね～。"
  robot.hear /不純物/i, (msg) -> msg.send "不確定性原理によって生じたものね～。"
  robot.hear /不確定性原理/i, (msg) -> msg.send "神の恣意的な所作ね～。"
  robot.hear /神の恣意的な所作/i, (msg) -> msg.send "統一理論の介在を許さないのね～。"
  robot.hear /自然主義/i, (msg) -> msg.send "あらゆるものが自然物に依存しているのね～。"
  robot.hear /イチンダー/i, (msg) -> msg.send "ツラニ帝国の皇帝ね～。"
  robot.hear /ツラニ帝国/i, (msg) -> msg.send "ケレワンにある国ね～。"
  robot.hear /ウルティマ/i, (msg) -> msg.send "ロードブリティッシュね～。"
  robot.hear /ロードブリティッシュ/i, (msg) -> msg.send "王様ね～。"
  robot.hear /ホッブズ/i, (msg) -> msg.send "主権が君主にあると考えた人ね～。"
  robot.hear /紀貫之/i, (msg) -> msg.send "土佐日記を書いた人ね～。"
  robot.hear /土佐日記/i, (msg) -> msg.send "かな文学ね～。"
  robot.hear /更級日記/i, (msg) -> msg.send "かな文学ね～。"
  robot.hear /泉式部日記/i, (msg) -> msg.send "日記文学ね～。"
  robot.hear /国民投票/i, (msg) -> msg.send "レファレンダムね～。"
  robot.hear /斉藤由貴/i, (msg) -> msg.send "サイコー由鬼ね～。"
  robot.hear /サイコー由鬼/i, (msg) -> msg.send "ドテラマンね～。"
  robot.hear /ミケドニア/i, (msg) -> msg.send "多元宇宙ね～。"
  robot.hear /ウッドヘッド/i, (msg) -> msg.send "狂王トレボーね～。"
  robot.hear /トレボー/i, (msg) -> msg.send "狂王ね～。"
  robot.hear /立憲君主党/i, (msg) -> msg.send "ヴァレンヌ事件かと思っちゃった～。"
  robot.hear /ソロモン王/i, (msg) -> msg.send "ダビデの子ね～。"
  robot.hear /ダビデの子/i, (msg) -> msg.send "イスラエルの王様ね～。"
  robot.hear /ニーチェ/i, (msg) -> msg.send "「ツァラトゥストラはかく語りき」ね～。"
  robot.hear /ツァラトゥストラ/i, (msg) -> msg.send "実存主義の先駆者ね～。"
  robot.hear /ジョイス/i, (msg) -> msg.send "ジェームス・ジョイスはイギリスの小説家で、心理義文学の創始者なのよね～。"
  robot.hear /ABM/i, (msg) -> msg.send "ICBMの迎撃ミサイルね～。"
  robot.hear /スプリント/i, (msg) -> msg.send "アメリカの大気圏内近距離高加速ABMね～。"
  robot.hear /スパータン/i, (msg) -> msg.send "アメリカの大気圏外遠距離用ABMね～。"
  robot.hear /ガロッシュ/i, (msg) -> msg.send "旧ソ連の大気圏外遠距離用ABMね～。"
  robot.hear /ガゼル/i, (msg) -> msg.send "旧ソ連の新型ABMね～。"
  robot.hear /ノメンクラツーラ/i, (msg) -> msg.send "旧ソ連の特権階級ね～。"
  robot.hear /ヒス/i, (msg) -> msg.send "アルジャー・ヒスはアメリカ国務省の元官吏なんだけど、旧ソ連のスパイだったのよね～。"
  robot.hear /FOBS/i, (msg) -> msg.send "部分軌道爆撃方式ね～。"
  robot.hear /シンドラー/i, (msg) -> msg.send "ベートーヴェンの弟子ね～。"
  robot.hear /ボーヴォワール/i, (msg) -> msg.send "実存主義哲学の代表的な作家ね～。"
  robot.hear /実存主義哲学/i, (msg) -> msg.send "本質に先行する、実存を中心概念とする哲学ね。"
  robot.hear /実存/i, (msg) -> msg.send "神という絶対者にささえられない、人間の自覚的な存在～。"
  robot.hear /象徴主義/i, (msg) -> msg.send "サンボリズムは、自由主義文学の反動なのよね～。"
  robot.hear /リムパック/i, (msg) -> msg.send "アメリカ海軍第三艦隊が主催して、環太平洋諸国軍が参加する合同演習ね～。"
  robot.hear /ISDN/i, (msg) -> msg.send "いったい・それ・どないする・ねん!"
  robot.hear /ターミナルソフト/i, (msg) -> msg.send "88TERM、BeeTERM、CCT98、CTERM、ESTERM、JET-TERMINAL、KERMIT、VersaLINK、WTERM、アシストターム、かたろう、まいと～く……"
  robot.hear /SFマガジン/i, (msg) -> msg.send "400号は、2,500円もしたのよ!"
  robot.hear /ブレグジット/i, (msg) -> msg.send "以前EMS(欧州通貨制度)にイギリスが大ブーイングだったことを考えると、EU離脱はそんなに不思議じゃないのかもね～。"
  robot.hear /EU/i, (msg) -> msg.send "ヨーロッパ連合ね～。"
  robot.hear /EC/i, (msg) -> msg.send "ヨーロッパ共同体ね～。"
  robot.hear /地域的経済統合/i, (msg) -> msg.send "ALADI、ASEAN、COMECON、EFTA、OECD、SAARC、SELA……"
  robot.hear /EFTA/i, (msg) -> msg.send "ヨーロッパ自由貿易連合ね～。"
  robot.hear /OECD/i, (msg) -> msg.send "経済協力開発機構ね～。"
  robot.hear /COMECON/i, (msg) -> msg.send "経済相互援助会議ね～。"
  robot.hear /ALADI/i, (msg) -> msg.send "ラテンアメリカ統合連合ね～。"
  robot.hear /SELA/i, (msg) -> msg.send "ラテンアメリカ経済機構ね～。"
  robot.hear /ASEAN/i, (msg) -> msg.send "東南アジア諸国連合ね～。"
  robot.hear /ECSC/i, (msg) -> msg.send "欧州石炭鉄鉱共同体ね～。"
  robot.hear /EEC/i, (msg) -> msg.send "欧州経済共同体ね～。"
  robot.hear /EURATOM/i, (msg) -> msg.send "欧州原子力共同体ね～。"
  robot.hear /SEA/i, (msg) -> msg.send "単一欧州議定書ね～。"
  robot.hear /CAP/i, (msg) -> msg.send "ECの共通農業政策ね～。"
  robot.hear /ECU/i, (msg) -> msg.send "欧州通貨単位って、実際の貨幣は存在しないのよね～。"
  robot.hear /VAT/i, (msg) -> msg.send "付加価値税ね～。"
  robot.hear /MSAC/i, (msg) -> msg.send "1973年の石油危機で最も深刻な影響を受けた「最貧国」ね～。"
  robot.hear /UNCTAD/i, (msg) -> msg.send "国連貿易開発会議って先進資本主義諸国と後発発展途上国の経済格差、つまり南北問題が顕在化したところなのよね～。ここから資源ナショナリズムという考え方出て来たと思うの～。"
  robot.hear /資源ナショナリズム/i, (msg) -> msg.send "天然資源の恒久主権よね～。"
  robot.hear /OPEC/i, (msg) -> msg.send "石油輸出国機構って、メジャーに対抗してつくられた発展途上国側の組織なのよね～。"
  robot.hear /メジャー/i, (msg) -> msg.send "エクソン・モービル・シェブロン・テキサコ・ガルフ・BP・シェルのセブン・シスターズね!"
  robot.hear /立憲君主制/i, (msg) -> msg.send "制限君主制で、憲法に従って君主が統治権を行使する君主制ね～。"
  robot.hear /社会民主主義/i, (msg) -> msg.send "プロレタリアートの独裁から見ると異端よね～。"
  robot.hear /視程/i, (msg) -> msg.send "大気の混濁度を表す尺度で、視程距離は肉眼で目標を確認できる最大距離ね～。"
  robot.hear /PSI/i, (msg) -> msg.send "大量破壊兵器拡散防止構想ね～。"
  robot.hear /アバヤ/i, (msg) -> msg.send "女性が着る、髪や肌を隠す衣装ね～。"
  robot.hear /アザーン/i, (msg) -> msg.send "お祈りの時間を告げる呼びかけね～。"
  robot.hear /メッカ/i, (msg) -> msg.send "カーバ神殿は、創始者ムハンマドが神の言葉を授かった場所なのよね～。"
  robot.hear /メディナ/i, (msg) -> msg.send "メディナは、ムハンマドがイスラム教を広めた場所なのよね～。"
  robot.hear /ミフラーブ/i, (msg) -> msg.send "お祈りの方向を示す壁のくぼみは、聖地メッカの方角なのよね～。"
  robot.hear /イマーム/i, (msg) -> msg.send "イスラム教の導師ね～。"
  robot.hear /ハラル食品/i, (msg) -> msg.send "イスラム教の戒律に従って処理された食品ね～。"
  robot.hear /ムフティー/i, (msg) -> msg.send "イスラム法学者ね～。"
  robot.hear /シャリア/i, (msg) -> msg.send "イスラム法ね～。"
  robot.hear /無垢/i, (msg) -> msg.send "日本の男って、イノセントに弱いわよね～。"
  robot.hear /カマトト/i, (msg) -> msg.send "イノセントを売り物にして男に媚びる女って怖～い。"
  robot.hear /インフラストラクチャー/i, (msg) -> msg.send "生活関連社会資本と産業関連社会資本ね～。"
  robot.hear /シグマシステム/i, (msg) -> msg.send "しーっ!"
  robot.hear /CFE/i, (msg) -> msg.send "欧州通常戦力ね～。"
  robot.hear /景気後退/i, (msg) -> msg.send "リセッションって、もう誰も言わないわよね～。"
  robot.hear /SS-24/i, (msg) -> msg.send "旧ソ連のICBMスカルベルね～。"
  robot.hear /SS-19/i, (msg) -> msg.send "スティレットね～。"
  robot.hear /SS-11/i, (msg) -> msg.send "シーゴね～。"
  robot.hear /タイタン/i, (msg) -> msg.send "アメリカのICBMって、大きいわよね～。"
  robot.hear /SURTASS/i, (msg) -> msg.send "曳航群列監視システムは、ASWセンターに設置されているのよね～。"
  robot.hear /MRM/i, (msg) -> msg.send "中距離AAMね～。"
  robot.hear /AAM/i, (msg) -> msg.send "空対空ミサイルね～。"
  robot.hear /SRM/i, (msg) -> msg.send "短距離AAMね～。"
  robot.hear /フロッグ/i, (msg) -> msg.send "WPOのSNFね～。"
  robot.hear /WPO/i, (msg) -> msg.send "ワルシャワ条約機構って、いまどき誰か知ってるの?"
  robot.hear /SNF/i, (msg) -> msg.send "短距離核兵器ね～。"
  robot.hear /NATO/i, (msg) -> msg.send "北大西洋条約機構は、いまだしぶとく残っているわよね～。"
  robot.hear /プルトン/i, (msg) -> msg.send "フランスのSNFね～。"
  robot.hear /スカッド/i, (msg) -> msg.send "実質、SS-1よね～。"
  robot.hear /CSI/i, (msg) -> msg.send "競争戦略構想ね～。"
  robot.hear /ATACMS/i, (msg) -> msg.send "アメリカのCSIの中心となる通常弾頭付戦術ミサイルね～。"
  robot.hear /TERCOM/i, (msg) -> msg.send "地形照合誘導装置ね～。"
  robot.hear /DSMAC/i, (msg) -> msg.send "デシタル地形相関装置ね～。"
  robot.hear /AS15/i, (msg) -> msg.send "旧ソ連のALCMね～。"
  robot.hear /ASX19/i, (msg) -> msg.send "旧ソ連で実験中だった、大型のALCMね～。"
  robot.hear /SS-4/i, (msg) -> msg.send "サンダルね～。"
  robot.hear /サンダル/i, (msg) -> msg.send "SS-4ね～。"
  robot.hear /スキーン/i, (msg) -> msg.send "SS-6ね～。"
  robot.hear /SS-6/i, (msg) -> msg.send "旧ソ連のLRINFね～。"
  robot.hear /LRINF/i, (msg) -> msg.send "長射程INFね～。"
  robot.hear /BGM109G/i, (msg) -> msg.send "アメリカのLRINFね～。"
  robot.hear /SS-12/i, (msg) -> msg.send "旧ソ連のSRINFね～。"
  robot.hear /SRINF/i, (msg) -> msg.send "短射程INFね～。"
  robot.hear /SSBS/i, (msg) -> msg.send "フランスのIRBMね～。"
  robot.hear /DF3型/i, (msg) -> msg.send "中国のIRBMね～。"
  robot.hear /SS-CX-4/i, (msg) -> msg.send "旧ソ連のGLCMね～。"
  robot.hear /GLCM/i, (msg) -> msg.send "地上発射巡航ミサイルね～。"
  robot.hear /NDS/i, (msg) -> msg.send "NACSTARに装備されている、核爆発探知装置ね～。"
  robot.hear /NAVSTAR/i, (msg) -> msg.send "アメリカの軍事偵察衛星ね～。"
  robot.hear /NMCC/i, (msg) -> msg.send "国家軍事指揮センターね～。"
  robot.hear /NEACP/i, (msg) -> msg.send "国家非常事態空中指揮所ね～。"
  robot.hear /MRBM/i, (msg) -> msg.send "準中距離弾道ミサイルね～。"
  robot.hear /IRBM/i, (msg) -> msg.send "中距離弾道ミサイルね～。"
  robot.hear /JCS/i, (msg) -> msg.send "統合参謀本部ね～。"
  robot.hear /統合参謀本部/i, (msg) -> msg.send "アメリカ大統領とNSCに、軍事的な助言をする機関のことね～。"
  robot.hear /NSC/i, (msg) -> msg.send "国家安全保障会議ね～。"
  robot.hear /SAC/i, (msg) -> msg.send "アメリカの戦略空軍ね～。"
  robot.hear /NORAD/i, (msg) -> msg.send "クリスマスになるとサンタを追跡する、北米大陸防空宇宙軍ね～。"
  robot.hear /BMEWS/i, (msg) -> msg.send "位相段列型レーダーを用いた、弾道ミサイル早期警戒システムね～。"
  robot.hear /COBRA-DANE/i, (msg) -> msg.send "新型の位相段列型レーダーね～。"
  robot.hear /PAWS/i, (msg) -> msg.send "アメリカのSLBM警戒用の位相段列型レーダーね～。"
  robot.hear /ミニットマン/i, (msg) -> msg.send "ミニットマンはLGM30、ミニットマン2はLGM30F、ミニットマン3はLGM30Gね～。"
  robot.hear /F-22/i, (msg) -> msg.send "ラプターね～。"
  robot.hear /V-22/i, (msg) -> msg.send "CV-22はアメリカ空軍向け、MV-22はアメリカ海兵隊向けね～。"
  robot.hear /OTHレーダー/i, (msg) -> msg.send "遠距離レーダーね～。"
  robot.hear /ROTHER/i, (msg) -> msg.send "OTHレーダーの原理を使ったレーダーね～。"
  robot.hear /POMCUS/i, (msg) -> msg.send "海外事前配置軍需物資ね～。"
  robot.hear /USCENTCOM/i, (msg) -> msg.send "1990年代、湾岸情勢の悪化で中東機動軍が創設されたのよね～。"
  robot.hear /USSPACECOM/i, (msg) -> msg.send "統合宇宙軍ね～。"
  robot.hear /JSTARS/i, (msg) -> msg.send "統合監視目標攻撃レーダーシステムね～。"
  robot.hear /ミゼットマン/i, (msg) -> msg.send "アメリカの小型ICBMね～。"
  robot.hear /ピースキーパー/i, (msg) -> msg.send "アメリカのICBMね～。"
  robot.hear /スティンガー/i, (msg) -> msg.send "アメリカの携帯用SAMね～。"
  robot.hear /E3A/i, (msg) -> msg.send "セントリーね～。"
  robot.hear /セントリー/i, (msg) -> msg.send "アメリカのAWACSね～。"
  robot.hear /オライオン/i, (msg) -> msg.send "P3Cね～。"
  robot.hear /LRAACA/i, (msg) -> msg.send "長距離対潜哨戒機ね～。"
  robot.hear /ビンセンス/i, (msg) -> msg.send "ペルシャ湾でイランの旅客機を誤射、撃墜しちゃったわね～。"
  robot.hear /BGM109A/i, (msg) -> msg.send "TLAM-Nね～。"
  robot.hear /TLAM-N/i, (msg) -> msg.send "陸上攻撃型の核弾頭付きSLCMね～。"
  robot.hear /BGM109B/i, (msg) -> msg.send "TASMね～。"
  robot.hear /TASM/i, (msg) -> msg.send "艦対艦攻撃型の通常弾頭付きSLCMね～。"
  robot.hear /プラウダ/i, (msg) -> msg.send "旧ソ連共産党中央委員会の日刊機関誌ね～。"
  robot.hear /毎日新聞/i, (msg) -> msg.send "外務省公電漏洩事件(沖縄密約電文漏洩事件)で、社内経営が悪化しちゃったわね～。"
  robot.hear /アイデア/i, (msg) -> msg.send "イデー、観念とか理念ね～。"
  robot.hear /ラッサール/i, (msg) -> msg.send "ドイツの社会主義者で、労働者階級の国家理念の実現を主張したのよね～。"
  robot.hear /理念/i, (msg) -> msg.send "理想的な状態を考える概念ね～。"
  robot.hear /理想的/i, (msg) -> msg.send "物事の状態が理想に合致している様子ね～。"
  robot.hear /プラトン/i, (msg) -> msg.send "ソクラテスの弟子で形而上学の確立者ね～。観念論哲学って、なんだろ～。"
# robot.hear /ソクラテス/i, (msg) -> msg.send "古代ギリシアの哲学者ね～。"
  robot.hear /ギリシア哲学/i, (msg) -> msg.send "タレス、ソクラテス、アリストテレス。あとストア学派プラトンね～。"
  robot.hear /ソクラテス学派/i, (msg) -> msg.send "キニク派、キュレネ派、プラトン派?"
  robot.hear /観念論哲学/i, (msg) -> msg.send "観念論は経験論の反対ね～。"
  robot.hear /経験論/i, (msg) -> msg.send "意識に先立つ実在を認めない立場。唯物論の反対ね～。"
# robot.hear /実在/i, (msg) -> msg.send "客観的に存在するものね～。"
  robot.hear /実在論/i, (msg) -> msg.send "意識を超えた独立の実在を認める立場。経験論の反対ね～。"
  robot.hear /ソクラテス的イロニー/i, (msg) -> msg.send "無知を装って相手の無知を明かす論法ね～。"
  robot.hear /ソクラテスの弁明/i, (msg) -> msg.send "プラトンの著作ね～。"
  robot.hear /PVO/i, (msg) -> msg.send "航空宇宙軍。旧ソ連の防空軍ね～。"
  robot.hear /SS-25/i, (msg) -> msg.send "旧ソ連の移動式ICBMね～。"
  robot.hear /ICBM/i, (msg) -> msg.send "大陸間弾道ミサイルね～。"
  robot.hear /フラットツイン/i, (msg) -> msg.send "ボーンショツね～。"
  robot.hear /ボーンショツ/i, (msg) -> msg.send "ヘンハウス・レーダーね～。"
  robot.hear /ヘンハウス/i, (msg) -> msg.send "旧ソ連の弾道ミサイル探知レーダーね～。"
  robot.hear /無線測位方式/i, (msg) -> msg.send "電波を使った目標の方位の測定ね～。"
  robot.hear /雇用機会/i, (msg) -> msg.send "たとえば、失業対策事業とか。"
  robot.hear /失業対策事業/i, (msg) -> msg.send "職業安定法による職業紹介制度とか。"
  robot.hear /福祉国家/i, (msg) -> msg.send "夜警国家の反対ね～。"
  robot.hear /夜警国家/i, (msg) -> msg.send "自由放任主義的な国家を批判した、ラッサールの言葉ね～。"
  robot.hear /評論/i, (msg) -> msg.send "物事の是非・善悪・優劣・美醜を批評し、論じることね～。"

# robot.hear /単語/i, (msg) -> msg.send "説明"

